# Site settings
title: "The Relativity Transit"
logo: logo.png
email: ogderoge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Relativity Transit is weblog about programming, design, photography, and more.
url: "http://rogerogden.github.io" # the base hostname & protocol for your site
baseurl: "/home" # the subpath of your site, e.g. /blog/
twitter_username: _rogerogden
github_username:  rogerogden

# Build settings
markdown: kramdown

#Required gems for Github Pages
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
