# Site settings
title: "The Relativity Transit"
logo: logo.png 
email: ogderoge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roon was an excellent service, with a beautiful understated design. Roon
  was eventually acquired by Ghost, who awesomely chose to open source the theme.
  <br/>This is my Jekyll port of the Roon theme
url: "http://rogerogden.github.io" # the base hostname & protocol for your site
baseurl: "/home" # the subpath of your site, e.g. /blog/
twitter_username: _rogerogden
github_username:  rogerogden

# Build settings
markdown: kramdown
